export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE';

// const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
// const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
// const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE';
