export const Todo = 'Todo';
export const InProgress = 'InProgress';
export const Done = 'Done';

export const GET_TODO_REQUEST = 'GET_TODO_REQUEST';
export const GET_TODO_SUCCESS = 'GET_TODO_SUCCESS';
export const GET_TODO_FAILURE = 'GET_TODO_FAILURE';

export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE';

export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE';

export const DELETE_SUBTASK_REQUEST = 'DELETE_SUBTASK_REQUEST';
export const DELETE_SUBTASK_SUCCESS = 'DELETE_SUBTASK_SUCCESS';
export const DELETE_SUBTASK_FAILURE = 'DELETE_SUBTASK_FAILURE';

export const TOGGLE_SUBTASK_REQUEST = 'TOGGLE_SUBTASK_REQUEST';
export const TOGGLE_SUBTASK_SUCCESS = 'TOGGLE_SUBTASK_SUCCESS';
export const TOGGLE_SUBTASK_FAILURE = 'TOGGLE_SUBTASK_FAILURE';

export const CHANGE_PROGRESS_REQUEST = 'CHANGE_PROGRESS_REQUEST';
export const CHANGE_PROGRESS_SUCCESS = 'CHANGE_PROGRESS_SUCCESS';
export const CHANGE_PROGRESS_FAILURE = 'CHANGE_PROGRESS_FAILURE';

export const ADD_FILTER_BY_TAG = 'ADD_FILTER_BY_TAG';
